### ISSUE TITLE
 Issues with running prolog2curry: missing modules?

### ISSUE THREAD

**Issue by william-vw** [curry-packages/prolog2curry#1]
I'm quite eager to try out the conversion of Prolog to a functional (logic) language. (My long-term goal is to attempt a transformation to an imperative language, or, at least, see how far I can get.) I found my way here after reading the [associated paper](https://www.cambridge.org/core/journals/theory-and-practice-of-logic-programming/article/from-logic-to-functional-logic-programs/AB29BDA26F960E605C4B6C74384ADD21).

After installing pakcs (and haskell), trying to run the prolog2curry module gives me the following errors:

```
Prelude> :load prolog2curry/src/Main.curry
Switching to directory "prolog2curry/src"...
Compiling Curry program "Main"...

Language/Prolog/Read.curry:18:8-18:27 Error:
    Interface for module Language.Prolog.Show not found
    | 
 18 | import Language.Prolog.Show  ( showPlProg, showPlClause, showPlTerm )
    |        ^^^^^^^^^^^^^^^^^^^^

Language/Prolog/Read.curry:19:8-19:28 Error:
    Interface for module Language.Prolog.Types not found
    | 
 19 | import Language.Prolog.Types
    |        ^^^^^^^^^^^^^^^^^^^^^
ERROR occurred during parsing!
```

(Disclaimer - I'm not sure whether this is the right way to run the module.)

I know these are found in the `prolog` module, but, when trying to add the relevant files from there, I get the following error:

```
Prelude> :add prolog/src/Language/Prolog/Types.curry
ERROR: Illegal module name: prolog/src/Language/Prolog/Types
ERROR: Source file of module "prolog/src/Language/Prolog/Types.curry" not found!
```

The contents of that folder under `pakcs`:
```
% ls prolog/src/Language/Prolog/
Goodies.curry	Show.curry	Types.curry
```

Using the following syntax (I believe this is suggested in the manual?)
```
Prelude> :add prolog
ERROR: Source file of module "prolog" not found!
```

I am clearly missing something :-)

**Comment by mihanus** [comment]
Yes, you missed something :-)

Since this is a Curry package and has some dependencies, it cannot be loaded/compiled by just loading
the main file. If you have already installed PAKCS, you also find in the `bin` directory the executable `cypm`
of the Curry Package Manager (CPM).  If you never used `cypm`, the following way should work:

Initialize CPM's repository index by

    > cypm update

If you already downloaded the source code of this package (otherwise you can also do it by
`cypm checkout prolog2curry`), go into its main directory `prolog2curry` and run

    > cypm install

This downloads all dependencies, compiles the main program and generates the executable `pl2curry` in the
directory `~/.cpm/bin`. If you add this into your path, you can run the translator by executing `pl2curry` with appropriate arguments (see `pl2curry --help`).

If you only want to load the source code of the translator (e.g., to modify and try it manually), you can also
install the package by

    > cypm install --noexec

and start PAKCS by

    > pakcs :load Main

Note that `pakcs` sets the CURRYPATH with all necessary directories, in particular, `src`, using `cypm`.
Therefore, you don't need to use `:load src/Main` (and it is also not recommended to do it).

I hope this helps!

**Comment by william-vw** [comment]
that works, many thanks :-)
